{{- if .Values.stage003 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.clusterName }}-scheduler-kubeconfig
  namespace: {{ .Values.global.namespace }}
data:
  scheduler.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/kubernetes/pki/ca.crt
        server: https://{{ .Values.global.clusterName }}:6443
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /etc/kubernetes/pki/scheduler.crt
        client-key: /etc/kubernetes/pki/scheduler.key
{{- end }}
